# Generated by Django 6.0.6 on 2026-07-19 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodDonation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('food_name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=50)),
                ('quantity', models.CharField(max_length=100)),
                ('pickup_address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('expiry_time', models.TimeField()),
                ('food_image', models.ImageField(upload_to='food_images/')),
                ('status', models.CharField(default='Available', max_length=20)),
            ],
        ),
    ]
