# Generated by Django 6.0.6 on 2026-07-23 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0003_helpsupport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fooddonation',
            name='status',
        ),
    ]
