# Generated by Django 6.0.6 on 2026-08-04 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0005_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooddonation',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Completed', 'Completed')], default='Pending', max_length=20),
        ),
    ]
