# Generated by Django 6.0.6 on 2026-08-12 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0009_alter_fooddonation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooddonation',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
