# Generated by Django 6.0.6 on 2026-08-17 04:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0011_donationrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ngo',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ngo', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ngo',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
