from django.urls import path
from . import views
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)

urlpatterns = [
    path('', views.home, name='home'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('donate-food/', views.donate_food, name='donate_food'),
    path('donation/', views.donation, name='donation'),
    path('history/', views.history, name='history'),
    path('ngo/', views.ngo, name='ngo'),
    path( "ngo/<int:ngo_id>/",views.ngo_detail,name="ngo_detail"),
    path('setting/', views.setting, name='setting'),
    path('profile/', views.profile, name='profile'),
    path('about/', views.about, name='about'),
    path('help-support/', views.help_support, name='help_support'),
    path('login/', views.login_view, name='login'),
    path('signup/', views.signup, name='signup'),
    path('logout/', views.logout_view, name='logout'),
    path("ngo-dashboard/", views.ngo_dashboard, name="ngo_dashboard"),
    path('accept/<int:id>/', views.accept_donation, name='accept_donation'),
    path('reject/<int:donation_id>/', views.reject_donation, name='reject_donation'),
    path('donation-detail/<int:donation_id>/', views.donation_detail, name='donation_detail'),
    path('forgot-password/', views.forgot_password, name='forgot_password'),
    path('verify-otp/', views.verify_otp, name='verify_otp'),
    path('reset-password/', views.reset_password, name='reset_password'),
    path('api/donations/', views.donation_api, name='donation_api'),
    path('api/update-donation/<int:id>/', views.update_donation_api, name='update_donation_api'),
    path('api/delete-donation/<int:id>/',views.delete_donation_api,name='delete_donation_api'),
    path('api/signup/', views.signup_api, name='signup_api'),
    path('api/login/', views.login_api, name='login_api'),
    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('donation/<int:donation_id>/accept/', views.accept_donation, name='accept_donation'),
    path('donation/<int:donation_id>/complete/',views.complete_donation,name='complete_donation'),
    path('api/donation/<int:donation_id>/accept/', views.accept_donation, name='accept_donation_api'),
    path('api/create-donation/', views.create_donation_api, name='create_donation_api'),
    path("ngo/<int:ngo_id>/request/",views.request_donation,name="request_donation"),
    path("ngo/<int:ngo_id>/send-request/",views.send_donation_request,name="send_donation_request"),
    path("ngo/<int:ngo_id>/request/<int:donation_id>/",views.request_donation,name="request_donation"),
    path("request-failed/", views.request_failed, name="request_failed"),
    path("ngo-donations/",views.ngo_donations,name="ngo_donations"),
    path("ngo/profile/",views.ngo_profile,name="ngo_profile"),
    path("ngo/impact-reports/",views.impact_reports,name="impact_reports"),
    path("donation-requests/",views.donation_requests,name="donation_requests"),
    path("donation-list/",views.donation_list,name="donation_list"),
    path("ngo-profile/edit/",views.edit_ngo_profile,name="edit_ngo_profile"),
    path("ai/recommendation/",views.ai_recommendation,name="ai_recommendation"),
    path("notification/",views.notification,name="notification"),
]
